---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == 'RedHat' or
      ansible_os_family == 'Debian'
  tags:
    - logstash_assert

- name: Create Logstash YUM repo file
  yum_repository:
    name: elastic
    description: Elastic YUM repo
    baseurl: "{{ logstash_yum_repo_url }}"
    gpgkey: "{{ logstash_yum_repo_key }}"
    params: "{{ logstash_yum_repo_params }}"
  when: >
    ansible_os_family == 'RedHat'
  tags:
    - logstash_pkg
    - logstash_yumrepo

- name: Install Logstash GPG key
  apt_key:
    url: "{{ logstash_apt_repo_key }}"
  when: >
    ansible_os_family == 'Debian'
  tags:
    - logstash_pkg
    - logstash_aptrepo

- name: Create Logstash APT repo file
  apt_repository:
    repo: "{{ logstash_apt_repo_string }}"
  when: >
    ansible_os_family == 'Debian'
  tags:
    - logstash_pkg
    - logstash_aptrepo

- name: Install additional Logstash packages
  package:
    name: "{{ item }}"
  with_items: "{{ logstash_additional_pkgs }}"
  notify:
    - Restart Logstash service
  tags:
    - logstash_pkg

- name: Install Logstash package
  package:
    name: "{{ logstash_pkg }}"
  register: logstash_pkg_status
  notify:
    - Restart Logstash service
  tags:
    - logstash_pkg

- name: Configure Logstash startup options
  template:
    src: startup.options.j2
    dest: "{{ logstash_startup_options_file }}"
  register: logstash_startup_options_state
  notify:
    - Restart Logstash service
  tags:
    - logstash_config
    - logstash_startup_options

- name: Re-run system-install
  shell: >
    {{ logstash_startup_options_ls_home }}/bin/system-install {{ logstash_startup_options_file }}
  when: >
    logstash_startup_options_state is defined and
    logstash_startup_options_state | changed
  register: logstash_system_install_status
  tags:
    - logstash_config
    - logstash_startup_options

- name: Configure Logstash
  template:
    src: logstash.yml.j2
    dest: "{{ logstash_config_file }}"
  notify:
    - Restart Logstash service
  tags:
    - logstash_config
    - logstash_config_main

- name: Configure Logstash pipeline
  template:
    src: logstash.conf.j2
    dest: "{{ logstash_pipeline_path }}/{{ item.key }}.conf"
  with_dict: "{{ logstash_pipeline }}"
  notify:
    - Restart Logstash service
  tags:
    - logstash_config
    - logstash_config_parser

- name: Configure Logstash JVM options
  template:
    src: jvm.options.j2
    dest: "{{ logstash_jvm_options_file }}"
  notify:
    - Restart Logstash service
  tags:
    - logstash_config
    - logstash_jvm_options

- name: Configure Logstash sysconfig
  template:
    src: logstash.sysconfig.j2
    dest: "{{ logstash_sysconfig_file }}"
  notify:
    - Restart Logstash service
  when: >
    ansible_os_family == 'RedHat'
  tags:
    - logstash_config
    - logstash_jvm_sysconfig

- name: Reload systemd daemon
  systemd:
    name: "{{ logstash_service }}"
    daemon_reload: yes
  when: >
    ansible_service_mgr == 'systemd' and
    logstash_system_install_status is defined and
    logstash_system_install_status | changed
  tags:
    - logstash_service

- name: Enable Logstash service
  service:
    name: "{{ logstash_service }}"
    enabled: yes
  tags:
    - logstash_service

- name: Start Logstash service
  service:
    name: "{{ logstash_service }}"
    state: started
  register: logstash_service_started
  tags:
    - logstash_service
